### PR TITLE
Update to MC 1.12.x

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**

### CODE REVIEW

**Comment by bonii-xx** [comment]
Right, I forgot about this, due to being busy with lots of other things. Thanks for updating, did you test it on a server?

**Comment by Shadows-of-Fire** [comment]
I don't remember actually.  Changes didn't seem like they would've broken a server, but this was a while ago so its out of my memory.

**Comment by bonii-xx** [comment]
I'll check it as soon as I have a dev environment back up then.

**Comment by bonii-xx** [comment]
Looks good, time to get a release out. Thanks for updating, sorry for the delay 👍

**Pull request merged**
